"""empty message

Revision ID: 0253d01cbef9
Revises: 
Create Date: 2019-06-21 14:17:09.879904

"""
from alembic import op
import sqlalchemy as sa

import app
# revision identifiers, used by Alembic.
revision = '0253d01cbef9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created', app.lib.utility_sqlalchemy.AwareDateTime(), nullable=True),
    sa.Column('updated', app.lib.utility_sqlalchemy.AwareDateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('member', 'admin', name='role_types', native_enum=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=30), server_default='', nullable=False),
    sa.Column('sign_in_count', sa.Integer(), nullable=False),
    sa.Column('current_sign_in_on', app.lib.utility_sqlalchemy.AwareDateTime(), nullable=True),
    sa.Column('current_sign_in_ip', sa.String(length=45), nullable=True),
    sa.Column('last_sign_is_on', app.lib.utility_sqlalchemy.AwareDateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('payment_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('subscriptions',
    sa.Column('created', app.lib.utility_sqlalchemy.AwareDateTime(), nullable=True),
    sa.Column('updated', app.lib.utility_sqlalchemy.AwareDateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=128), nullable=True),
    sa.Column('coupon', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
